config/routes.rb
Rails.application.routes.draw do
  resources :people do
    member do
      get "spoofemail"
      post "whatsapp"
    end
  end
  get 'welcome/index'
  resources :countries
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :country
  def pic=(uploaded_io)
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
    end
    write_attribute(:pic,uploaded_io.original_filename)
  end
  def pic
    read_attribute(:pic)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy spoofemail whatsapp ]

  # GET /people or /people.json
  def whatsapp
     threads=[]
     pic = 'hi.png' 
     message = 'hi.png'
     caption='caption'
     phone='+777'
     myvalue=""
     threads << Thread.new { Thread.current[:output] =`cd #{Rails.root.to_s}/spoof && echo 'spoof whatsapp' && python3 ./whatsapp.py \'#{phone}\' \'#{message or ""}\' \'#{pic or ""}\' \'#{caption or ''}\'` }#jj
     threads.each do |t|
         t.join
         myvalue << t[:output]
      end
      p myvalue
      redirect_to person_url(@person), notice: "Person was spoofed (whatsapp)."
  end
  def spoofemail
      UserMailer.with(user: @person).welcome_email.deliver_later
      redirect_to person_url(@person), notice: "Person was spoofed (email)."

  end
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:fullname, :pic, :phone, :country_id, :email)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fullname, style: "display: block" %>
    <%= form.text_field :fullname %>
  </div>

  <div>
    <%= form.label :pic, style: "display: block" %>
    <%= form.file_field :pic %>
  </div>

  <div>


    <%= form.label :country_id, style: "display: block" %>
    and
    <%= form.label :phone, style: "display: block" %>

  </div>

  <div>
    <%= form.select :country_id, Country.all.collect {|x|["#{x.unicode} (#{x.phone})".html_safe, x.id]} %>
    <%= form.telephone_field :phone %>


  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Fullname:</strong>
    <%= person.fullname %>
  </p>

  <p>
    <strong>Pic:</strong>
    <%= person.pic %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= person.phone %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= person.country_id %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="infoperson">
  <img src="/uploads/<%= @person.pic %>"/>
  <h2><%=@person.fullname%></h2>
  <p class="phone"><%=@person.country.unicode.html_safe%> <%=@person.country.phone%> <%=@person.phone%></p>
  <p class="email"> <%=@person.email%></p>
        </div>

<div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col">
          <div class="card">
                  <img src="..." class="card-img-top" alt="...">
                        <div class="card-body">
                                  <h5 class="card-title">Spoof email</h5>
                                  <p class="card-text"><%=link_to "spoof email",spoofemail_person_path(@person)%></p>
                                                </div>
                                                    </div>
                                                      </div>
                                                        <div class="col">
                                                              <div class="card">
                                                                      <img src="..." class="card-img-top" alt="...">
                                                                            <div class="card-body">
                                                                                      <h5 class="card-title">Card title</h5>
                                                                                              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                                                                                    </div>
                                                                                                        </div>
                                                                                                          </div>
                                                                                                            <div class="col">
                                                                                                                  <div class="card">
                                                                                                                          <img src="..." class="card-img-top" alt="...">
                                                                                                                                <div class="card-body">
                                                                                                                                          <h5 class="card-title">Spoof whatsapp</h5>
                                                                                                                                          <form action="<%=whatsapp_person_path(@person)%>" method="post">
                                                                                                                                            <input type="hidden" name="phone" value="<%=@person.country.phone%><%=@person.phone%>"/> 
                                                                                                                                            <div >
                                                                                                                                              <label for="message">
                                                                                                                                                message
                                                                                                                                              </label>
                                                                                                                                              <textarea name="message" id="message">
                                                                                                                                              </textarea>
                                                                                                                                            </div>
                                                                                                                                            <div >
                                                                                                                                              <label for="pic">
                                                                                                                                                pic
                                                                                                                                              </label>
                                                                                                                                              <select name="pic" id="pic">
                                                                                                                                              </select>
                                                                                                                                            </div>
                                                                                                                                            <div >
                                                                                                                                              <label for="caption">
                                                                                                                                                caption
                                                                                                                                                
                                                                                                                                              </label>
                                                                                                                                              <input type="text" name="caption" id="caption"/>
                                                                                                                                            </div>
                                                                                                                                          </form>
                                                                                                                                                        </div>
                                                                                                                                                            </div>
                                                                                                                                                              </div>
                                                                                                                                                                <div class="col">
                                                                                                                                                                      <div class="card">
                                                                                                                                                                              <img src="..." class="card-img-top" alt="...">
                                                                                                                                                                                    <div class="card-body">
                                                                                                                                                                                              <h5 class="card-title">Card title</h5>
                                                                                                                                                                                                      <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                  </div>
</div>
<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>