config/routes.rb
Rails.application.routes.draw do
  resources :people do
    member do
      get "spoofemail"
      post "whatsapp"
    end
  end
  get 'welcome/index'
  resources :countries
  devise_for :users, controllers: { registrations: 'users/registrations',sessions: 'users/sessions' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpoofMessage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                              </button>
                                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                            <%if user_signed_in?%>     <li class="nav-item">
                                                <%= button_to "logout", destroy_session_path(current_user), :method => :delete, :class => "nav-link"%>
                                                                        </li>
                                                                      <%else%>
                                                                                <li class="nav-item">
                                                                                            <a class="nav-link" href="/users/sign_in">connecter</a>
                                                                                                    </li>
                                                                                <li class="nav-item">
                                                                                            <a class="nav-link" href="/users/sign_up">s'inscrire</a>
                                                                                                    </li>
                                                                      <%end%>
                                                                                <li class="nav-item">
                                                                                            <a class="nav-link" href="/countries">voir tous les Pays, drapeaux et indicatif</a>
                                                                                                    </li>
                                                                                                    <%if user_signed_in?%>
                                                                                                            <li class="nav-item dropdown">
                                                                                                                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                                                                                          <%=image_tag(asset_path("hacker"), width:50, height:50)%> <%=current_user.email%> 
                                                                                                                                                </a>
                                                                                                                                                          <ul class="dropdown-menu">
                                                                                                                                                            <li><%=current_user.country.unicode.html_safe%> <%=current_user.country.phone%> <%=current_user.number%></li>

                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                              </li>
                                                                                                                                                                      <%end%>
                                                                                                                                                                                                                                      <li class="nav-item">
                                                                                                                                                                                                                                        <a class="nav-link " href="<%=people_path%>">Personnes</a>
                                                                                                                                                                                                                                                          </li>
                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                      <form class="d-flex" role="search">
                                                                                                                                                                                                                                                                                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                                                                                                                                                                                                                                                                                        <button class="btn btn-outline-success" type="submit">Search</button>
                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                    </div>
    </nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>